version: '3.9'

networks:
  default:
    external: true
    name: ${INT_NETWORK}

services:


#
# === Elasticsearch ===
#
  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    container_name: "${APP_HOST}-${APP_ID}-elasticsearch-exporter"
    hostname: "elasticsearch-exporter.${APP_HOST}.${INT_NETWORK}"
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      - default
    ports:
      - "9114:9114"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [
      "--es.uri=http://elastic:changeme@host.docker.internal:9200"
    ]

#
# === Nginx Prometheus Exporter ===
#
#   nginx-exporter:
#   # https://stackoverflow.com/questions/64952485/nginx-prometheus-exporter-container-cannot-connect-to-nginx
#     image: nginx/nginx-prometheus-exporter
#     container_name: "${APP_HOST}-${APP_ID}-nginx-exporter"
#     hostname: "nginx-exporter.${APP_HOST}.${INT_NETWORK}"
#     restart: ${DOCKER_RESTART_POLICY}
#     networks:
#       - default
#     ports:
#       - "${NGINX_EXPORTER_PORT}:9113"
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     command:
#       - -nginx.scrape-uri=http://host.docker.internal:${NGINX_PORT}/stub_status

#
# === Prometheus ===
#
  prometheus:
    image: docker.io/bitnami/prometheus:${PROMETHEUS_VERSION}
    container_name: "${APP_HOST}-${APP_ID}-prometheus"
    hostname: "${APP_HOST}.${INT_NETWORK}"
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      - default
    ports:
      - "${MONITOR_PORT}:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./certs/ca.crt:/opt/bitnami/prometheus/conf/ca.crt
      - ./conf/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ./data/prometheus:/opt/bitnami/prometheus/data:rw

#
# === Grafana ===
#
  grafana:
    image: docker.io/bitnami/grafana:${GRAFANA_VERSION}
    container_name: "${APP_HOST}-${APP_ID}-grafana"
    hostname: "grafana.${APP_HOST}.${INT_NETWORK}"
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GRAFANA_PORT="${GRAFANA_PORT}"
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./conf/grafana/grafana.ini:/opt/bitnami/grafana/conf/grafana.ini
      - ./conf/grafana/default.ini:/opt/bitnami/grafana/conf/defaults.ini
      - ./data/grafana:/opt/bitnami/grafana/data:rw
