# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["host.docker.internal:9090"]

  # - job_name: "nginx"
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ["host.docker.internal:9113"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    metrics_path: "/metrics"
    scheme: http
    # tls_config:
    #   ca_file: "/opt/bitnami/prometheus/conf/ca.crt"
    #   insecure_skip_verify: true
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "platypus"
    scrape_interval: 5s
    metrics_path: "/q/metrics"
    scheme: http
    # tls_config:
    #   ca_file: "/opt/bitnami/prometheus/conf/ca.crt"
    #   insecure_skip_verify: true
    static_configs:
      - targets: ["not.intranet.local:8086"]

  - job_name: "pt"
    scrape_interval: 5s
    metrics_path: "/q/metrics"
    scheme: http
    # tls_config:
    #   ca_file: "/opt/bitnami/prometheus/conf/ca.crt"
    #   insecure_skip_verify: true
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "mamka"
    scrape_interval: 5s
    metrics_path: "/q/metrics"
    scheme: https
    tls_config:
      ca_file: "/opt/bitnami/prometheus/conf/ca.crt"
      insecure_skip_verify: true
    static_configs:
      - targets: ["mamka.intranet.local:443"]

  - job_name: "cdcp"
    scrape_interval: 5s
    metrics_path: "/q/metrics"
    scheme: https
    tls_config:
      ca_file: "/opt/bitnami/prometheus/conf/ca.crt"
      insecure_skip_verify: true
    static_configs:
      # - targets: ["not.intranet.local:28088"]
      - targets: ["host.docker.internal:28448"]

  - job_name: "u1"
    scrape_interval: 5s
    metrics_path: "/q/metrics"
    scheme: https
    tls_config:
      ca_file: "/opt/bitnami/prometheus/conf/ca.crt"
      insecure_skip_verify: true
    static_configs:
      # - targets: ["not.intranet.local:48088"]
      - targets: ["host.docker.internal:48448"]

  - job_name: "u2"
    scrape_interval: 5s
    metrics_path: "/q/metrics"
    scheme: https
    tls_config:
      ca_file: "/opt/bitnami/prometheus/conf/ca.crt"
      insecure_skip_verify: true
    static_configs:
      # - targets: ["not.intranet.local:58088"]
      - targets: ["host.docker.internal:58448"]

  - job_name: "gui-api"
    scrape_interval: 5s
    metrics_path: "/q/metrics"
    static_configs:
      - targets: ["not.intranet.local:58060"]

  # - job_name: "es01"
  #   scrape_interval: 5s
  #   metrics_path: "/metrics"
  #   static_configs:
  #     - targets: ["host.docker.internal:9114"]

  - job_name: "corda-cdcp"
    scrape_interval: 5s
    static_configs:
      - targets: ["not.intranet.local:7005"]

  - job_name: "corda-notary"
    scrape_interval: 5s
    static_configs:
      - targets: ["not.intranet.local:7006"]

  - job_name: "corda-u1"
    scrape_interval: 5s
    static_configs:
      - targets: ["not.intranet.local:7007"]

  - job_name: "corda-u2"
    scrape_interval: 5s
    static_configs:
      - targets: ["not.intranet.local:7008"]

  # - job_name: "wildfly"
  #   scrape_interval: 5s
  #   metrics_path: "/q/metrics"
  #   static_configs:
  #     - targets: ["host.docker.internal:9990"]

